name: CI

on:
  push:
    branches:
      - master
      - 2201.[0-9]+.x
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Build Module Examples
      - name: Ballerina Examples Build
        run: chmod +x ./examples/build.sh && ./examples/build.sh build
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Test Ballerina Project
      - name: Ballerina Test
        run: bal test ./ballerina --test-report --code-coverage --coverage-format=xml
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
